[build]
pre-build = ["dpkg --add-architecture $CROSS_DEB_ARCH", """ \
    apt-get update && \
    apt-get --assume-yes install \
        libiio-dev:$CROSS_DEB_ARCH \
        libsensors4-dev:$CROSS_DEB_ARCH"""]
